#!/bin/sh


start() {
    printf 'Loading aesdchar.'
    /aesdchar_load
    status=$?
    if [ "$status" -eq 0 ]; then
         echo "OK"
    else
         echo "FAIL"
    fi
    return "$status"
}

stop() {
  printf 'Unloading aesdchar'
  /aesdchar_unload
  status=$?
  if [ "$status" -eq 0 ]; then
    echo "OK"
  else
    echo "FAIL"
  fi
  return "$status"
}

restart() {
  printf 'Reloading aesdchar'
  /aesdchar_unload || true
  /aesdchar_load
  status=$?
  if [ "$status" -eq 0 ]; then
    echo "OK"
  else
    echo "FAIL"
  fi
  return "$status"
}





case "$1" in
     start|stop|restart)
         "$1";;
     reload)
         # Restart, since there is no true "reload" feature.
         restart;;
     *)
         echo "Usage: $0 {start|stop|restart|reload}"
         exit 1
 esac


			
